version: "3"

services:
  web:
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://droneuser:drone_password@db:5432/dronedb
    depends_on:
      - db
    networks:
      - drone-net
    command: bash -c "sleep 2 && ./entrypoint.sh"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=droneuser
      - POSTGRES_PASSWORD=drone_password
      - POSTGRES_DB=dronedb
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - drone-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U droneuser -d dronedb" ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres_data:

networks:
  drone-net:  # Explicit network declaration
    driver: bridge
